"""removed contact_number from shipping info, it should go on the billing instead

Revision ID: 0787d919f2b1
Revises: a752183eda09
Create Date: 2023-01-04 20:37:36.175345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0787d919f2b1'
down_revision = 'a752183eda09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shippings', 'contact_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shippings', sa.Column('contact_number', sa.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
