"""added column to inventory

Revision ID: bfa87d2c5f1d
Revises: 666d24fe84fb
Create Date: 2022-12-23 10:19:26.174575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa87d2c5f1d'
down_revision = '666d24fe84fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('preview', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'preview')
    # ### end Alembic commands ###