"""added a logo column to inventory

Revision ID: cec5a8d60766
Revises: 105ce555e281
Create Date: 2022-12-28 12:58:51.748617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec5a8d60766'
down_revision = '105ce555e281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('logo', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'logo')
    # ### end Alembic commands ###