"""added category column to inventory

Revision ID: 105ce555e281
Revises: bfa87d2c5f1d
Create Date: 2022-12-28 09:51:56.086670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105ce555e281'
down_revision = 'bfa87d2c5f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('category', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'category')
    # ### end Alembic commands ###