"""added contact_number and primary keys to shippings table

Revision ID: a752183eda09
Revises: 56966e941326
Create Date: 2023-01-04 17:58:09.206523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a752183eda09'
down_revision = '56966e941326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shippings', sa.Column('primary', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shippings', 'primary')
    # ### end Alembic commands ###
